apiVersion: v1
kind: Service
metadata:
  name: cicd-demo-service
  namespace: default
spec:
  selector:
    app: devops          # Matches your deployment pod label
  ports:
    - protocol: TCP
      port: 80            # Exposes port 80 inside the cluster
      targetPort: 80      # Routes to containerPort 80 of the pod
  type: ClusterIP         # Default service type (internal-only)
