name: Test and Build

on:
  push:
    branches:
      - main
    paths:
      - '**/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setting up environment
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Setup
        uses: docker/setup-buildx-action@v2

      - name: Docker Credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker tag
        id: version
        run: |
          VERSION=v$(date +"%Y%m%d%H%M%S")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Build the Docker Image
      - name: Build Docker Image
        run: |
          docker build -t swarajmishra3184/cicd-demo:${{ env.VERSION }} .

      # Push the Docker Image
      - name: Push Docker Image
        run: |
          docker push swarajmishra3184/cicd-demo:${{ env.VERSION }}

      # Update the K8s Manifest Files
      - name: Update K8s Manifests
        run: |
          cat deploy/deployment.yaml
          sed -i "s|image: swarajmishra3184/cicd-demo:.*|image: swarajmishra3184/cicd-demo:${{ env.VERSION }}|g" deploy/deployment.yaml
          cat deploy/deployment.yaml

      # Commit the changes
      - name: Commit the changes
        run: |
          git config --global user.email "swaraj-mishra-22bcsb72@users.noreply.github.com"
          git config --global user.name "Github Actions Bot"
          git checkout main
          git add deploy/deployment.yaml
          git commit -m "Update deploy.yaml with new image version - ${{ env.VERSION }}"
          git push origin main